SELECT
	*
FROM
	PESSOA p
RIGHT OUTER JOIN CONTATO c2 
 ON
	( p.ID_PESSOA = c2.ID_CONTATO );
 
SELECT
	*
FROM
	PESSOA p
RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe 
 ON
	(pxpe.ID_PESSOA = p.ID_PESSOA )
RIGHT OUTER JOIN ENDERECO_PESSOA ep 
 ON
	(pxpe.ID_ENDERECO = ep.ID_ENDERECO);


SELECT
	*
FROM
	PESSOA p
RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe 
 ON
	(pxpe.ID_PESSOA = p.ID_PESSOA )
RIGHT OUTER JOIN ENDERECO_PESSOA ep 
 ON
	(pxpe.ID_ENDERECO = ep.ID_ENDERECO);

SELECT
	*
FROM
	PESSOA p
RIGHT OUTER JOIN CONTATO c 
ON
	(p.ID_PESSOA = c.ID_PESSOA)
RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe 
ON
	( c.ID_PESSOA = pxpe.ID_PESSOA)
RIGHT OUTER JOIN ENDERECO_PESSOA ep 
ON
	(pxpe.ID_ENDERECO = ep.ID_ENDERECO);
-- usei a propria formatação do dbeaver ctrl + shift + f

SELECT *
FROM
	PESSOA p
FULL OUTER JOIN CONTATO c  ON
	( c.ID_CONTATO 
       = p.ID_PESSOA );
      
SELECT
	*
FROM
	PESSOA p
FULL OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe 
 ON
	(pxpe.ID_PESSOA = p.ID_PESSOA )
FULL OUTER JOIN ENDERECO_PESSOA ep 
 ON
	(pxpe.ID_ENDERECO = ep.ID_ENDERECO);   


SELECT
	*
FROM
	PESSOA p
FULL OUTER JOIN CONTATO c 
 ON
	(p.ID_PESSOA = c.ID_PESSOA)
FULL OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe 
 ON
	( c.ID_PESSOA = pxpe.ID_PESSOA)
FULL OUTER JOIN ENDERECO_PESSOA ep 
 ON
	(pxpe.ID_ENDERECO = ep.ID_ENDERECO);
 

