SELECT
	*
FROM
	PESSOA p
RIGHT OUTER JOIN CONTATO c2
                          ON
	(p.ID_PESSOA = c2.ID_CONTATO);

SELECT
	*
FROM
	PESSOA p
RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe
                          ON
	(pxpe.ID_PESSOA = p.ID_PESSOA)
RIGHT OUTER JOIN ENDERECO_PESSOA ep
                          ON
	(pxpe.ID_ENDERECO = ep.ID_ENDERECO);


SELECT
	*
FROM
	PESSOA p
RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe
                          ON
	(pxpe.ID_PESSOA = p.ID_PESSOA)
RIGHT OUTER JOIN ENDERECO_PESSOA ep
                          ON
	(pxpe.ID_ENDERECO = ep.ID_ENDERECO);

SELECT
	*
FROM
	PESSOA p
RIGHT OUTER JOIN CONTATO c
                          ON
	(p.ID_PESSOA = c.ID_PESSOA)
RIGHT OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe
                          ON
	(c.ID_PESSOA = pxpe.ID_PESSOA)
RIGHT OUTER JOIN ENDERECO_PESSOA ep
                          ON
	(pxpe.ID_ENDERECO = ep.ID_ENDERECO);
-- usei a propria formata��o do dbeaver ctrl + shift + f

SELECT
	*
FROM
	PESSOA p
FULL OUTER JOIN CONTATO c ON
	(c.ID_CONTATO
        = p.ID_PESSOA);

SELECT
	*
FROM
	PESSOA p
FULL OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe
                         ON
	(pxpe.ID_PESSOA = p.ID_PESSOA)
FULL OUTER JOIN ENDERECO_PESSOA ep
                         ON
	(pxpe.ID_ENDERECO = ep.ID_ENDERECO);


SELECT
	*
FROM
	PESSOA p
FULL OUTER JOIN CONTATO c
                         ON
	(p.ID_PESSOA = c.ID_PESSOA)
FULL OUTER JOIN PESSOA_X_PESSOA_ENDERECO pxpe
                         ON
	(c.ID_PESSOA = pxpe.ID_PESSOA)
FULL OUTER JOIN ENDERECO_PESSOA ep
                         ON
	(pxpe.ID_ENDERECO = ep.ID_ENDERECO);



SELECT
	P.ID_PESSOA,
	P.NOME AS "PESSOAS COM ENDERE�O"
FROM
	PESSOA P
WHERE
	EXISTS
          (
	SELECT
		PXPE.ID_PESSOA
	FROM
		PESSOA_X_PESSOA_ENDERECO pxpe
	WHERE
		PXPE.ID_PESSOA = P.ID_PESSOA
          );

SELECT
	P.ID_PESSOA,
	P.NOME,
	EP.ID_ENDERECO,
	EP.LOGRADOURO
FROM
	PESSOA P
    LEFT OUTER JOIN PESSOA_X_PESSOA_ENDERECO PXPE
              ON
	P.ID_PESSOA = PXPE.ID_PESSOA
    LEFT OUTER JOIN ENDERECO_PESSOA EP
              ON
	PXPE.ID_ENDERECO = EP.ID_ENDERECO;
 

