SELECT * 
  FROM PAIS p 
 ORDER BY NOME DESC;

SELECT LOGRADOURO, CEP 
  FROM ENDERECO e  
 WHERE LOGRADOURO LIKE '%A%' OR LOGRADOURO LIKE '%a%';

SELECT * FROM ENDERECO e WHERE CEP LIKE '%0';

SELECT * FROM ENDERECO e WHERE NUMERO <= 100 AND NUMERO >= 1;

SELECT * FROM ENDERECO e WHERE UPPER(LOGRADOURO) LIKE 'RUA%' ORDER BY CEP DESC;

SELECT COUNT(ID_ENDERECO)
FROM ENDERECO e ;

SELECT COUNT(ID_ENDERECO)
FROM ENDERECO e GROUP BY ID_CIDADE ;


